### ISSUE TITLE
Polluting the environment and and perpetuating that in .profile..

### ISSUE THREAD

**Issue by triptec** [getredash/setup#19]
..when from what I can tell a simple cd would suffice should not be done.
And I would like to remind you that docker-compose has other usages than only running redash.

https://github.com/getredash/setup/blob/cb47626b6823cbafac407b3e8991e97f53121f6e/setup.sh#L64-L67

**Comment by amostsai** [comment]
I totally agree with what triptec said
A computer will also run some docker-compose projects at the same time

Especially when developing or practicing redash in our notebook
Writing in .profile will cause many people to be troubled
and waste a lot of their time debugging

I am one of the victim
In order to solve the strange problem that other projects cannot be executed
Find a lot of docker, docker-compose information
Finally, I had to delete the container, image of all the company's projects in the past
Remove docker and docker-compose software
reboot.....
It took me more ten hours to find out what happen! !
If it is not convenient to change the shell script
PLEASE, INDICATE THIS IN THE README! !
Thank you so much ~~~

**Comment by amostsai** [comment]
I totally agree with what triptec said
A computer will also run some docker-compose projects at the same time

Especially when developing or practicing redash in our notebook
Writing in .profile will cause many people to be troubled
and waste a lot of their time debugging

I am one of the victim
In order to solve the strange problem that other projects cannot be executed
Find a lot of docker, docker-compose information
Finally, I had to delete the container, image of all the company's projects in the past
Remove docker and docker-compose software
reboot.....
It took me more ten hours to find out what happen! !
If it is not convenient to change the shell script
PLEASE, INDICATE THIS IN THE README! !
Thank you so much ~~~

**Comment by justinclift** [comment]
We removed those Docker Compose project overrides yesterday (in https://github.com/getredash/setup/commit/b9ee472e57b0bb78e81f0bb187e5d46e4cb02a47), so I'm closing this issue. :smile:
