### ISSUE TITLE
Issue with the setup script 

### ISSUE THREAD

**Issue by tfain** [getredash/setup#51]
Hi, I grabbed the script and when I executed it, I saw the following errors: 

E: The repository 'http://us-central1.gce.archive.ubuntu.com/ubuntu kinetic Release' no longer has a Release                                                                                                        file.
E: The repository 'http://us-central1.gce.archive.ubuntu.com/ubuntu kinetic-updates Release' no longer has a                                                                                                        Release file.
E: The repository 'http://us-central1.gce.archive.ubuntu.com/ubuntu kinetic-backports Release' does not have                                                                                                        a Release file.
E: The repository 'http://security.ubuntu.com/ubuntu kinetic-security Release' no longer has a Release file.

**Comment by justinclift** [comment]
Hi @tfain, somehow I missed this issue.

Guessing you got it worked out?

Btw, that error message is the kind of thing that happens when a package server either gets a bad update, or it stops handling updates for a release for some reason.

Not sure if that was the case here, but (in theory) switching to a package server that's serving updates correctly would generally fix the problem. :smile:
