### ISSUE TITLE
When will stable CHANNEL be updated?

### ISSUE THREAD

**Issue by snickerjp** [getredash/setup#53]
# When will stable CHANNEL be updated?

in setup.sh
https://github.com/getredash/setup/blob/e611a6af966124eb974d1d953f64a10c5e9767e6/setup.sh#L63-L64

return **8.0.0.b32245**
```
$ curl -s "https://version.redash.io/api/releases?channel=stable" | json_pp | grep "docker_image" | head -n 1 | awk 'BEGIN{FS=":"}{print $3}' | awk 'BEGIN{FS="\""}{print $1}'
8.0.0.b32245
```

Is #11 relevant?

# Reason.

Because I would like to update my version of Redash.

However, if I go to setup.sh and get the version
replacement, so I cannot update it without modifying setup.sh.
https://github.com/getredash/setup/blob/e611a6af966124eb974d1d953f64a10c5e9767e6/setup.sh#L69

I would like to improve this situation.

**Comment by justinclift** [comment]
The setup script has been updated to just embed the desired version directly, rather than make any external calls.

We still need to create a new stable Redash release however, and/or update the setup script to work ok with the `preview` release until that's ready.

Thinking about it more, getting the `preview` image to work with the setup script is probably more urgent than the other stuff I was planning on doing next.  So, I'll look at it later on today. :smile:

**Comment by justinclift** [comment]
@snickerjp Would you be ok to try the `setup.sh` that's [in this PR](https://github.com/getredash/setup/pull/61)?

Direct download link: https://github.com/getredash/setup/raw/preview_v1/setup.sh

That setup.sh has a new `--preview` option makes it use the latest `preview` image from Docker Hub rather than the old official release.

In my initial testing so far, it's working ok. :smile:

**Comment by snickerjp** [comment]
Understood. I will give it a try!

**Comment by snickerjp** [comment]
@justinclift 

Result was OK.
I tried it in two environments.

- OS
  - Ubuntu 18.04
  - Ubuntu 22.04

- `sudo bash setup.sh --preview`
![image](https://github.com/getredash/setup/assets/1247622/5541e89f-4550-4943-9fa4-f041e75d8880)
![image](https://github.com/getredash/setup/assets/1247622/844c8b3f-92b8-44c2-aff9-28d564c042a0)

- `sudo bash setup.sh`
![image](https://github.com/getredash/setup/assets/1247622/0a39448c-d87e-4dc9-b53a-95cf4fb0b59b)

**Comment by justinclift** [comment]
Thanks, it looks like that PR is going in the right direction. :smile:

I still need to make some further improvements to it (and test it more too) before it's ready for merging though.

**Comment by justinclift** [comment]
@snickerjp That PR has been merged, as the `preview` release seems ok for people to use.

It hasn't had wide enough testing for it to be a new "STABLE" release though.  And we'd better make sure the upgrading process always works before we do that. :grimacing:

**Comment by snickerjp** [comment]
Thanks for fixing it.
